/**
 * @fileoverview gRPC-Web generated client stub for authentications
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: protos/authentications.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.authentications = require('./authentications_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authentications.AuthenticationsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.authentications.AuthenticationsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authentications.signUpRequest,
 *   !proto.authentications.signUpResponse>}
 */
const methodDescriptor_Authentications_signUp = new grpc.web.MethodDescriptor(
  '/authentications.Authentications/signUp',
  grpc.web.MethodType.UNARY,
  proto.authentications.signUpRequest,
  proto.authentications.signUpResponse,
  /**
   * @param {!proto.authentications.signUpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authentications.signUpResponse.deserializeBinary
);


/**
 * @param {!proto.authentications.signUpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authentications.signUpResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authentications.signUpResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authentications.AuthenticationsClient.prototype.signUp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authentications.Authentications/signUp',
      request,
      metadata || {},
      methodDescriptor_Authentications_signUp,
      callback);
};


/**
 * @param {!proto.authentications.signUpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authentications.signUpResponse>}
 *     Promise that resolves to the response
 */
proto.authentications.AuthenticationsPromiseClient.prototype.signUp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authentications.Authentications/signUp',
      request,
      metadata || {},
      methodDescriptor_Authentications_signUp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.authentications.signInRequest,
 *   !proto.authentications.signInResponse>}
 */
const methodDescriptor_Authentications_signIn = new grpc.web.MethodDescriptor(
  '/authentications.Authentications/signIn',
  grpc.web.MethodType.UNARY,
  proto.authentications.signInRequest,
  proto.authentications.signInResponse,
  /**
   * @param {!proto.authentications.signInRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.authentications.signInResponse.deserializeBinary
);


/**
 * @param {!proto.authentications.signInRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.authentications.signInResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.authentications.signInResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.authentications.AuthenticationsClient.prototype.signIn =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/authentications.Authentications/signIn',
      request,
      metadata || {},
      methodDescriptor_Authentications_signIn,
      callback);
};


/**
 * @param {!proto.authentications.signInRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.authentications.signInResponse>}
 *     Promise that resolves to the response
 */
proto.authentications.AuthenticationsPromiseClient.prototype.signIn =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/authentications.Authentications/signIn',
      request,
      metadata || {},
      methodDescriptor_Authentications_signIn);
};


module.exports = proto.authentications;

